# Generated by Django 5.2 on 2025-04-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
